### PR TITLE
Set up backend and add mongodb

### PR DESCRIPTION
**Pull request by terrancexin**
- Set up express+node backend
- Add mongoose
- Add eslint configs
- Update readme with mongodb and local set up
- Refactor Server folder and routes file

### CODE REVIEW

**Comment by Dereje1** [comment]
Looks good @terrancexin , but I have closed the PR because it is targeting master, could you submit a new one targeting dev ?

**Comment by terrancexin** [comment]
change destination to `development` branch

**Comment by terrancexin** [comment]
Fixed merge conflicts

**Review by eolculnamo2 — APPROVED** [review]

**Review by belcurv — APPROVED** [review]
Looks great. Approved.

**Pull request merged**
